# -*- coding: utf-8 -*-
"""1_基本輸入與輸出教學版(解答)20201022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D9OlTHxkmuKk41Pl0rhMwdIbuWVLZj1m

# 1.基本輸入與輸出

```
標準輸入(stdin)與標準輸出(stdout)
   python輸入:input()
   python輸出: print()
```
```
自主學習主題
   python格式化輸出技術
```
```
進階學習主題:
[10]讀取檔案(txt,csv,xslx,json,...)與輸出到檔案
[20]資料庫讀取與輸出
```
# 基礎輸入與輸出(Basic Input and Output)

## 基本輸入:讀取使用者的輸入

```
使用input時，會從標準輸入(stdin)中讀取輸入資料
這些資料是string字串型態{重要}
stdin==Standard Input
```

執行底下程式看看:
```
# -*- coding: utf-8 -*-
x = input('Enter your name:')
print('Hello, ' + x)

a = input("請輸入：")
a
```

###  使用Python內建的type()函數顯示資料型態

底下程式執行後結果為何?
```
type(a)
```

### 程式錯誤與更正
```
小明明正在學習python程式

老師出了一題
要輸入一個整數分數
然後加15後
輸出最後答案

底下是小明明的python程式
請指出底下的錯誤並更正
```
#### 小明明的python程式 執行後結果為何?
```
a = input("請輸入：")
a

b = a+15
b
```

```
TypeError :資料型態(data type)錯誤
```

#### 更正的 小明明python程式
```
如何讀取使用者輸入的整數===>使用eval()函數
            ===>也可以使用int()函數
```
底下程式執行後結果為何?
```
a = eval(input("請輸入："))
a
type(a)
```

寫下你更正的答案:

#### 超級重要:一次輸入多（兩）個資料

底下程式執行後結果為何?
```
a,b = eval(input("請輸入兩個數位："))
a,b
```
"""

# -*- coding: utf-8 -*-
x = input('Enter your name:')
print('Hello, ' + x)
 
a = input("請輸入：")
a

type(a)

a = input("請輸入：")
a
 
b = a+15
b

a = eval(input("請輸入："))
a
type(a)

a,b = eval(input("請輸入兩個數位："))
a,b